language: perl
perl:
    - "5.18"

after_success:
    - openssl aes-256-cbc -K $encrypted_82af4a1b80fd_key -iv $encrypted_82af4a1b80fd_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
    - echo $DEPLOY_KNOWNHOST >> ~/.ssh/known_hosts
    - eval `ssh-agent`
    - chmod 600 .travis/deploy_key
    - ssh-add .travis/deploy_key
    - ssh $DEPLOY_USER@$DEPLOY_HOST "mkdir -p $DEPLOY_DIRECTORY/M $DEPLOY_DIRECTORY/templates"
    - scp *.pl *.css $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY/
    - scp M/*.pm $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY/M/
    - scp _htaccess $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY/.htaccess
    - scp templates/*.html $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY/templates/
